spring.application.name=ItCareerElevatorFifthExercisePresenceMicroservice

server.port=8084

spring.mongodb.uri=${SPRING_MONGO_DB_URI:mongodb://localhost:27017/presence_db}

# --- Reduce logging level ---
#logging.level.root=warn